---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ing
  namespace: api
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: api-146.190.4.229.sslip.io
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: api-svc
              port:
                number: 3000

    - host: api-146.190.4.229.sslip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-v2-svc
                port:
                  number: 3000
