# docker compore build
# docker compose up -d
# to shut down all
# docker compose down
networks:
  #docker network
  mynet:

volumes:
    data-vol:

services:
  # docker run -d --mount type=volume, sec=data-vol, dst=/var/lib/mysql --network=mynet
  mydb:
    image: stackupiss:northwind-db:v1
    volumes:
      - type: volume
        source: data-vol
        target: /var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: changeit
        MYSQL_DATABASE: northwind
        MYSQL_USER: northwinduser
        MYSQL_PASSWORD: northwindpassword
    networks:
      - mynet
    # we dont have port, because we do not want to expose it outside of the network

  #docker run -d -p 8080:3000 -e .... --network=mynet
  myapp:
    image: stackupiss/northwind-app:v1
    environment:
      - DB_HOST=mydb
      - DB_USER=root
      - DB_PASSWORD=changeit
    ports:
        - 8080:3000
    networks:
      - mynet
    # This means that this will only start if mydb is started
    depends_on:
      mydb:
        condition: service_started
